# Generated by Django 3.1.1 on 2020-09-12 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0002_clase_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='descripcion',
            field=models.TextField(default='Sin Descripción'),
        ),
        migrations.AddField(
            model_name='clase',
            name='nombre_clase',
            field=models.TextField(default='Sin Nombre'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='descripcion',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salon'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.salon'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
