# Generated by Django 3.1.1 on 2020-09-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_auto_20200912_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='user',
            new_name='id_user',
        ),
    ]
