# Generated by Django 3.1.1 on 2020-09-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('clave', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=100, null=True)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_clase', models.TextField(default='Sin Nombre')),
                ('descripcion', models.TextField(default='Sin Descripción')),
                ('audio', models.FileField(null=True, upload_to='audios/')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.salon')),
            ],
        ),
    ]
