# Generated by Django 3.1.1 on 2020-09-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='id_user',
            new_name='user',
        ),
    ]
