# Generated by Django 3.1.1 on 2020-09-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_auto_20200913_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='id_clase',
            new_name='clase',
        ),
    ]
