# Generated by Django 3.1.1 on 2020-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_auto_20200913_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
    ]
