# Generated by Django 3.1.1 on 2020-09-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_auto_20200913_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
    ]
